tickers:
  - NVDA
start_date: "2024-06-20"
end_date: "2025-06-20"
benchmark: "SPY"
capital:
  amount: 10000
  currency: USD
rebalance_frequency: "1d"
retrain_frequency: "1y"
model_name: "xgboost"
prediction_horizon: 1
model_dir: "trained_model"
feature_dir: "feature_engineering_output"
metrics_dir: "trained_model"
performance_output: "ml_strategy_performance.csv"